version: "3.5"
services:
    ProductService:
        image: ${DOCKER_REGISTRY-}productservice:v1
        build:
            context: ./Product-service
            dockerfile: Dockerfile
        environment:
            - CONNECTIONSTRINGS__DEFAULTCONNECTION=Server=tcp:project1server.database.windows.net,1433;Initial Catalog=Project1-Database;Persist Security Info=False;User ID=nhvtmanh;Password=helloworld123@;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
        ports:
            - "4201:80"
    UserService:
        image: ${DOCKER_REGISTRY-}userservice:v1
        build:
            context: ./User-service
            dockerfile: Dockerfile
        environment:
            - CONNECTIONSTRINGS__DEFAULTCONNECTION=Server=tcp:project1server.database.windows.net,1433;Initial Catalog=Project1-Database;Persist Security Info=False;User ID=nhvtmanh;Password=helloworld123@;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
        ports:
            - "4202:80"
